"""empty message

Revision ID: 1c45473d1ffb
Revises: None
Create Date: 2015-08-05 14:01:51.950028

"""

# revision identifiers, used by Alembic.
revision = '1c45473d1ffb'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('abv', sa.Integer(), nullable=True),
    sa.Column('with_ice', sa.Boolean(), nullable=True),
    sa.Column('first_tried_on', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drinks')
    ### end Alembic commands ###
